---
abstract: 'Create a version4 signature for Amazon Web Services'
author:
  - 'Lincoln Stein <lincoln.stein@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: '0.4205'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: AWS-Signature4
provides:
  AWS::Signature4:
    file: lib/AWS/Signature4.pm
    version: '1.00'
requires:
  Digest::SHA: '5.47'
  LWP: '5.835'
  URI: '1.59'
  URI::QueryParam: '0'
resources:
  license: http://dev.perl.org/licenses/
version: '1.00'
